### ISSUE TITLE
unsafe variables

### ISSUE THREAD

**Issue by InoMurko** [ZanjeerPlatform/bargad#4]
Hi,

good work on the code!
One thing I noticed is that you're ignoring warnings about using unsafe variables which causes the code to behave differently using Elixir 1.6 or Elixir 1.7. For example _Bargad.Merkle.insert/2_, variables _root, left, right_ after the _If_ statement.

**Comment by farazhaider** [comment]
Thank you for browsing through the code.  And indeed 2 tests were failing on upgrading to Elixir 1.7, I'll push the fix soon.

**Comment by farazhaider** [comment]
Fixed in 50ea179
